### ISSUE TITLE
idčka 

### ISSUE THREAD

**Issue by ViktoriaAndr** [kacenka7/zivotopis#1]
Tu nepotrebuješ (a i inde v indexe) nepotrebuješ mať ID, lebo potom podľa neho ani nestyluješ
https://github.com/kacenka7/zivotopis/blob/a5ddee4a6fe8fe7324046e4e2220ab11573d2238/index.html#L39
Všetko, čo sa potom nepoužíva pri stylovaní len zbytočne zahlcuje kód.

**Comment by kacenka7** [comment]
Přes to ID funguje proklikávání z menu na jednotlivé sekce. Takhle to dělal Luděk v základech HTML a CSS
