### ISSUE TITLE
strong v html

### ISSUE THREAD

**Issue by ViktoriaAndr** [kacenka7/zivotopis#2]
https://github.com/kacenka7/zivotopis/blob/a5ddee4a6fe8fe7324046e4e2220ab11573d2238/index.html#L21
Nie je to vyslovene chyba, ale je lepšie nepoužívať strong v html, ale stylovať to v css, v tomto prípade pomocou `font-weight:bold;`
Tu si ešte v tomto prípade zvýraznila len svoje prvé meno. Predpokladám, že to nebol zámer.

**Comment by kacenka7** [comment]
Právě, že to záměr byl. Dělala jsem to v HTML, protože jsem nevěděla, jak v CSS udělat tučně jen to jméno...
